### ISSUE TITLE
[FEAT] 캘린더 뷰 기초셋팅

### ISSUE THREAD

**Issue by mdb1217** [NewMascota/Mascota-Android#7]
## 💡 Issue
캘린더 뷰 기초셋팅 완료하기!

## 📝 todo
- [ ] 뷰 셋팅(캘린더 제외)
- [ ] 로직 짜기(캘린더 제외)
- [ ] dataSourceModule 만들기
- [ ] dataSource 만들기(더미 데이터용)
